version: "3"
services:
  sqs-handler:
    container_name: sqs-handler
    build: .
    network_mode: host
    volumes:
      - .:/app
    command: python3 src/main.py --config configs/config.json
    deploy:
      restart_policy:
        condition: on-failure

  mongo:
    container_name: mongo
    image: mongo
    network_mode: host
    ports:
      - 27017:27017
    deploy:
      restart_policy:
        condition: on-failure